#!/bin/sh

# backup - Script run by crond to perform backups.

set -e # exit on errors

source /usr/lib/log.sh

backup_dir="$1"

if [ -z "$backup_dir" ]; then
    echo "USAGE: ./backup.sh <backup dir>"
    exit 1
fi

log "Starting backup"

if ! restic snapshots &> /dev/null; then
    log "Initializing repository"
    restic init --verbose || (log "Initializing repository failed"; exit 1)
fi

log "Backing up $backup_dir"
restic --verbose backup "$backup_dir" || \
    (log "Backing up $backup_dir failed"; exit 1)

if [ -n "$FORGET_ARGS" ]; then
    log "Forgetting old snapshots"
    restic forget --verbose $FORGET_ARGS || \
        (log "Forgetting old snapshots failed"; exit 1)
fi

log "Backup complete"
