#!/bin/sh

# runner - Default command for Docker container

set -e # exit on error

echo "$CRON backup /data 1>&2" > /var/spool/cron/crontabs/root

if [ -n "$PRUNE_CRON" ]; then
    echo "$PRUNE_CRON prune 1>&2" >> /var/spool/cron/crontabs/root
fi

crond -L /var/log/cron

tail -f /var/log/cron
